# workflow:
#   rules:
#   - if: $CI_COMMIT_BRANCH == "dev"
#     variables:
#       registry: $ci_registry
#       # registry_namespace: $CI_PROJECT_NAME

variables:
  registry: $ci_registry
  registry_namespace: "demo-project"
  registry_username: $ci_registry_username
  registry_password: $ci_registry_password
  gitlab_username: $ci_gitlab_username
  gitlab_password: $ci_gitlab_password
  # app_name: $CI_PROJECT_NAME
  app_name: "demo-project"
  app_version: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - deploy
  
docker_build:
  stage: build
  script:
    #- export # 打印内置变量
    - echo $registry/$registry_namespace/$app_name:$app_version
    - docker build -t $registry/$registry_namespace/$app_name:$app_version .
  # artifacts:
  #   paths:
  #     - $app_name
  # needs:
  #   - build_code

docker_push:
  stage: build
  script:
    - docker login -u $ci_registry_username -p $ci_registry_password $ci_registry
    - docker push $registry/$registry_namespace/$app_name:$app_version
    - docker logout $ci_registry
  needs:
    - docker_build

deploy_dev:
  stage: deploy
  before_script:
    - echo http://${gitlab_username}:${gitlab_password}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git remote set-url origin http://${gitlab_username}:${gitlab_password}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git config --global user.name "sundayhk"
    - git config --global user.email "sundayhk@gmail.com"
  script:
    - git checkout -B dev
    - git fetch origin
    - git reset --hard origin/dev
    - cd base
    - kustomize edit set image $app_name=$registry/$registry_namespace/$app_name:$app_version
    - cat kustomization.yaml
    - git commit -am '[skip ci] Dev image update'
    - git push origin dev
  needs:
    - docker_push