apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: argocd-demo-project
  name: argocd-demo-project
  labels:
    app: argocd-demo-project
  
spec:
  replicas: 4
  selector:
    matchLabels:
      app: argocd-demo-project
  template:
    metadata:
      name: argocd-demo-project
      labels:
        app: argocd-demo-project
    spec:
      containers:
        - name: argocd-demo-project
          image: argocd-demo-project:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
