resources:
- deployment.yaml
- service.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: argocd-demo-project
  newName: harbor.sundayhk.com/argocd-demo-project/argocd-demo-project
  newTag: 5fa3bce6
