resources:
- apidemo-deployment.yaml
- apidemo-service.yaml
- apidemo-ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: harbor.sundayhk.com/argocd-demo-project/argocd-demo-project
  newTag: 389d1595
