resources:
- deployment.yaml
- service.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: demo-project
  newName: harbor.sundayhk.com/demo-project/demo-project
  newTag: e99b9536
