apiVersion: v1
kind: Service
metadata:
  name: demo-project
  namespace: demo-project
  labels:
    app: demo-project
spec:
  type: NodePort
  ports:
  - name: demo-project-port
    port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: demo-project
